-- This file is generated by build.sh
local V = {}
local ChadV = require('custom.chadversion')

------ packer/opt ------

V.Comment_nvim                 = '2c26a00f32b190390b664e56e32fd5347613b9e2'
V.LuaSnip                      = 'a12441e0598e93e67235eba67c8e6fbffc896f06'
V.aerial_nvim                  = 'dd35fd75c480da0e0239d69a607aac1347c395c6'
V.base46                       = ChadV.base46
V.bufferline_nvim              = '68839d62785edfb4ff7a7b3c1e9f4b64d55749e8'
V.cmp_buffer                   = '62fc67a2b0205136bc3e312664624ba2ab4a9323'
V.cmp_nvim_lsp                 = 'affe808a5c56b71630f17aa7c38e15c59fd648a8'
V.cmp_nvim_lua                 = 'd276254e7198ab7d00f117e88e223b4bd8c02d21'
V.cmp_path                     = '466b6b8270f7ba89abd59f402c73f63c7331ff6e'
V.cmp_luasnip                  = 'a9de941bcbda508d0a45d28ae366bb3f08db2e36'
V.feline_nvim                  = '1ea42671c523a080a01c62c40c2c8e7fc0139a8f'
V.friendly_snippets            = '57274f4d87b9ccb961092b25560ba300f691e943'
V.gitsigns_nvim                = '4883988cf8b623f63cc8c7d3f11b18b7e81f06ff'
V.indent_blankline_nvim        = '42fe62eb8792e427b2c7b0e1fa1b0d9597baac89'
V.jaq_nvim                     = 'b0048dccaa00c90d1c559f9bb8fdda90d37d4adb'
V.lsp_signature_nvim           = '49837977e210959c552bf357dc40ce18fadca501'
V.null_ls_nvim                 = 'c59ea57dfd9bc0402a53ad2e2ad7f23467fdf06a'
V.nvim_autopairs               = '4a95b3982be7397cd8e1370d1a09503f9b002dbf'
V.nvim_cmp                     = '1cad1815e165c2b436f41a1ee20327701842a761'
V.nvim_colorizer_lua           = '6c8b1495c3d2034188cc67c18e2ae5e8343cd504'
V.nvim_lsp_installer           = 'ed999f0a555e83932f8e400c8830679c0bb499b8'
V.nvim_lspconfig               = '9278dfbb92f8e99c313ce58ddcff92bd0bce5c0c'
V.nvim_tree_lua                = '0c13bd76a897390a43e262d5716d5faa8367b8d8'
V.nvim_treesitter              = 'd810c386341fbf0d49895a2cdd6a2b63b945b71a'
V.nvim_web_devicons            = '8d2c5337f0a2d0a17de8e751876eeb192b32310e'
V.telescope_nvim               = 'd88b44ddf14670cffa9fdb1eaca7a0429a973653'
V.vim_matchup                  = '976ebfe61b407d0a75d87b4a507bf9ae4ffffbaa'

------ packer/start ------

V.extensions                   = ChadV.extensions
V.impatient_nvim               = '969f2c5c90457612c09cf2a13fee1adaa986d350'
V.packer_nvim                  = '00ec5adef58c5ff9a07f11f45903b9dbbaa1b422'
V.plenary_nvim                 = '968a4b9afec0c633bc369662e78f8c5db0eba249'
V.toggleterm_nvim              = '443afa9e02a5935be7e3cfc54ed94aae712f5f6c'

return V
