-- This file is generated by build.sh
local V = {}

V.NvChad                       = 'c7949aa3c3770d84dcc514d9138dc62c6e199d65'
V.base46                       = '168e5b08e730c0c98b9d9d1a02ff2df5c709edfe'
V.extensions                   = 'befbb67c31788c590c1c74e91596f8cba0e59fb2'
V.nvim_colorizer_lua           = '6c8b1495c3d2034188cc67c18e2ae5e8343cd504'

return V
