-- This file is generated by build.sh
local V = {}

------ packer/opt ------

V.Comment_nvim                 = 'cc87c89'
V.LuaSnip                      = '07cf1a1'
V.base46                       = '168e5b0'
V.bufferline_nvim              = '82e3598'
V.cmp_buffer                   = '12463cf'
V.cmp_nvim_lsp                 = 'affe808'
V.cmp_nvim_lua                 = 'd276254'
V.cmp_path                     = '466b6b8'
V.cmp_luasnip                  = 'a9de941'
V.feline_nvim                  = '3991842'
V.friendly_snippets            = 'fdb15f6'
V.gitsigns_nvim                = 'ada01db'
V.indent_blankline_nvim        = '8567ac8'
V.lsp_signature_nvim           = '2496aac'
V.null_ls_nvim                 = '5717fb7'
V.nvim_autopairs               = 'aea9131'
V.nvim_cmp                     = '6e1e386'
V.nvim_colorizer_lua           = '6c8b149'
V.nvim_lsp_installer           = '4ed43f1'
V.nvim_lspconfig               = 'b86a37c'
V.nvim_tree_lua                = 'b2ba6de'
V.nvim_treesitter              = 'b8fd5df'
V.nvim_web_devicons            = '0c5b6d1'
V.packer_nvim                  = '4dedd3b'
V.telescope_nvim               = '1a91238'
V.vim_matchup                  = '485e711'

------ packer/start ------

V.aerial_nvim                  = '498c033'
V.extensions                   = '063d47a'
V.impatient_nvim               = 'bcc2250'
V.nvterm                       = 'bfef0fd'
V.plenary_nvim                 = '1da13ad'

return V
